- 03-water/water-section-two/water-section-two.css
- 03-water/water-section-two/water-section-two.html
- 03-water/water-section-two/water-section-two.js
this pull request adds the collapsible content to water-section-two
> water section two collapsible content

- 03-water/water-section-three/water-section-three.css
- 03-water/water-section-three/water-section-three.html
- 03-water/water-section-three/water-section-three.js
this pull request adds the collapsible content to water-section-three
> water section three collapsible content

- 03-water/water-section-one/water-section-one.css
water section one images did not have display block applied, this corrects that.
> fixed images with display block

- 08-prototypes/branch-example/branch-example.md
here is a pull request for the branch example
> added folder and file to branch example

- 03-water/water-section-five/water-section-five.css
- 03-water/water-section-five/water-section-five.html
- 03-water/water-section-five/water-section-five.js
this pull request adds the collapsible content to water-section-five
> water section five collapsible content

- 03-water/water-section-six/water-section-six.css
- 03-water/water-section-six/water-section-six.html
- 03-water/water-section-six/water-section-six.js
this pull request adds the collapsible content to water-section-six
> water section six collapsible content

- 07-combined-preview/03-water/index.html
attempt to dynamically loads stylesheets, components and then scripts...
> dynamic loading of stylesheets, components and scripts

- 03-water/water-section-four/water-section-four.css
- 03-water/water-section-four/water-section-four.html
this pull request provides a complete build of water-section-four with images
> water section four build and images complete

- 07-combined-preview/01-home/index.html
- 07-combined-preview/02-electric/index.html
- 07-combined-preview/04-gas/index.html
this pull request converts static stylesheet loading to dynamic
> dynamic stylesheet loading

- 01-home/home-hero/home-hero.css
- 01-home/home-hero/home-hero.html
- 01-home/home-section-one/home-section-one.css
- 01-home/home-section-one/home-section-one.html
- 01-home/home-section-two/home-section-two.css
- 01-home/home-section-two/home-section-two.html
this pull request revises the original home components
> home components revised

- 01-home/home-section-two/home-section-two.html
> renamed title and subtitle

- 03-water/water-hero/water-hero.css
- 03-water/water-section-five/water-section-five.css
- 03-water/water-section-four/water-section-four.css
- 03-water/water-section-one/water-section-one.css
- 03-water/water-section-six/water-section-six.css
- 03-water/water-section-three/water-section-three.css
- 03-water/water-section-two/water-section-two.css
this pull request toggles off the image-container background and the image background
> toggled off image container background and image background

- 02-electric/electric-calculator/electric-calculator.css
- 02-electric/electric-calculator/electric-calculator.html
- 02-electric/electric-calculator/electric-calculator.js
created an entirely new electric calculator
> added new calculator

- 02-electric/electric-calculator/electric-calculator.css
- 02-electric/electric-calculator/electric-calculator.html
- 02-electric/electric-calculator/electric-calculator.js
minor refactoring of html/css/js
> Electric calculator revision

- 00-overall/04-footer/footer.css
- 00-overall/04-footer/footer.html
revised the footer, adjusted element nesting, adjusted class names, etc.
> Footer revision

- 00-overall/02-header/header.css
- 00-overall/02-header/header.html
this pr makes initial minor revisions to the header
> header initial revisions

- 01-home/home-section-one/home-section-one.css
- 01-home/home-section-one/home-section-one.html
this pull request revises the home-section-one(and-two-three?)) to the updated design, including desktop media queries
> home-section-one revised

- 02-electric/electric-section-one/electric-section-one.css
- 02-electric/electric-section-one/electric-section-one.html
may its better to review last commit, which is include mobile and desktop
> Electric section one mobile and desktop done

- 02-electric/electric-section-two/electric-section-two.css
- 02-electric/electric-section-two/electric-section-two.html
I have tried to fix this one regarding your request on section one, as you review it if there is some thing i will fix, but untill you don't  merge it i won't be able to add images.
> section two mobile and desktop done

- 03-water/water-hero/water-hero.css
- 03-water/water-hero/water-hero.html
this pull request revises the water hero, and adds a desktop conversion
> water hero desktop conversion

- 00-overall/00-global-styles/global-styles.css
- 01-home/home-hero/home-hero.css
- 01-home/home-hero/home-hero.html
- 02-electric/electric-hero/electric-hero.css
- 02-electric/electric-hero/electric-hero.html
- 03-water/water-hero/water-hero.css
- 03-water/water-hero/water-hero.html
- 04-gas/gas-hero/gas-hero.css
- 04-gas/gas-hero/gas-hero.html
Added style to Hero Sections across website. Design phase still in progress.
> Hero sections
